Run `kap init` if any of the default commands are missing
kapetacom/local-cluster-service pull request #94
Opened 2023-10-31 19:00 UTC by andertun

2023-10-31 19:33 UTC, hofmeister requested changes

2023-10-31 19:33 UTC, hofmeister commented on src/utils/commandLineUtils.ts
> +    return taskManager.add(
If we want to do it like this - we should probably not make id a "task" - since this will show up for the user every time they start

2023-10-31 19:33 UTC, hofmeister commented on index.ts
> +                asyncListeningListener().catch((err) => console.error('Failed to run asyncListenListener', err));
Can't we just wrap things in try catch ? ".catch" hurts my eyes :)

2023-10-31 19:34 UTC, andertun commented on src/utils/commandLineUtils.ts
> +    return taskManager.add(
Where does it show up? What can we do instead?

2023-10-31 19:39 UTC, andertun commented on index.ts
> +                asyncListeningListener().catch((err) => console.error('Failed to run asyncListenListener', err));
Yes but it would need to be something like this then because I need to await the the result... 

```ts
(async () => {
    try {
        await asyncListeningListener();
    } catch (error) {
        console.error('Failed to run asyncListenListener', error);
    }
})();
```

2023-10-31 19:46 UTC, hofmeister commented on src/utils/commandLineUtils.ts
> +    return taskManager.add(
just make it a normal await thing - it'll show up in the notifications UI if you make it a "task"

2023-10-31 19:47 UTC, hofmeister commented on index.ts
> +                asyncListeningListener().catch((err) => console.error('Failed to run asyncListenListener', err));
Yup exactly - that's way clearer imo

2023-10-31 20:18 UTC, hofmeister requested changes

2023-10-31 20:18 UTC, hofmeister commented on index.ts
> +            currentServer.listen(port, bindHost, function listeningListener() {
Still not understanding the rewrite here - why did you change the callback from an async function to a sync - and then created an inner async function to call ?

2023-10-31 20:18 UTC, hofmeister commented on index.ts
> +            currentServer.listen(port, bindHost, function listeningListener() {
E.g. you rewrote the entire callback - not sure I understand why - when you could simply add the small piece of functionality ?

2023-10-31 20:28 UTC, andertun commented on index.ts
> +            currentServer.listen(port, bindHost, function listeningListener() {
The type for the callback is expected to be `() => void` and what we had was an async function that returns a Promise. 

<img width="1007" alt="image" src="https://github.com/kapetacom/local-cluster-service/assets/1045799/a10e73a3-e804-43b5-8f1c-71afbee70c67">

vs

<img width="621" alt="image" src="https://github.com/kapetacom/local-cluster-service/assets/1045799/e3f26c6b-001e-4b3e-aaaf-c25fdd7fc7b8">

2023-10-31 20:39 UTC, andertun commented on index.ts
> +            currentServer.listen(port, bindHost, function listeningListener() {
The eslint error was because the callback provided to `server.listen()` is expected to be synchronous and not return a promise. However, we had marked the callback as `async`, which makes it implicitly return a `Promise<void>` instead of just `void`.

One way to solve this is to encapsulate the asynchronous code within a separate `async` function that we invoke from within the callback. This way, we don't return anything from the callback directly, and we can handle the promise separately.

2023-10-31 21:24 UTC, hofmeister commented on index.ts
> +            currentServer.listen(port, bindHost, function listeningListener() {
This is one of those cases where honering eslint in my opinion makes the code worse / less readable :) I'd put a ts-ignore on it

2023-10-31 23:11 UTC, andertun commented on index.ts
> +            currentServer.listen(port, bindHost, function listeningListener() {
This one is actually not a typescript error. It's just the eslint rule `@typescript-eslint/no-misused-promises` that points out we did something unexpected. 

I have changed the eslint rule now so it allows us to pass in an async function where a sync function is expected.

```
'@typescript-eslint/no-misused-promises': [
    'error',
    {
        checksVoidReturn: {
            arguments: false,
        },
    },
]
```

2023-11-01 15:05 UTC, hofmeister approved these changes

2023-11-01 15:11 UTC, merged